adding more columns to QBRecord
QuickBase/interview-demos pull request #16
Opened 2018-08-30 15:09 UTC by sergioharo

preventing interviewees from doing just a basic index on the string value

2018-08-30 17:03 UTC, Kunjan commented
Yes thank you for doing this. After the last interview, I think this will help.

2018-08-30 17:03 UTC, Kunjan approved these changes

2018-08-30 17:04 UTC, Kunjan requested changes
The current Readme file has a DeleteByRecordID, do you want to change that?

2018-09-04 18:55 UTC, sergioharo commented
@Kunjan made changes

2018-09-04 19:09 UTC, Kunjan approved these changes

2018-09-04 19:19 UTC, merged